// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class GatewaySettings {
    /**
     * Creates a new GatewaySettings instance.
     * @param {Partial<GatewaySettings>} [$$source = {}] - The source object to create the GatewaySettings.
     */
    constructor($$source = {}) {
        if (!("baseUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseUrl"] = "";
        }
        if (!("defaultAgentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultAgentId"] = "";
        }
        if (!("programPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["programPath"] = "";
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GatewaySettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GatewaySettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GatewaySettings(/** @type {Partial<GatewaySettings>} */($$parsedSource));
    }
}

export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("gateway" in $$source)) {
            /**
             * @member
             * @type {GatewaySettings}
             */
            this["gateway"] = (new GatewaySettings());
        }
        if (!("workspace" in $$source)) {
            /**
             * @member
             * @type {WorkspaceSettings}
             */
            this["workspace"] = (new WorkspaceSettings());
        }
        if (!("ui" in $$source)) {
            /**
             * @member
             * @type {UISettings}
             */
            this["ui"] = (new UISettings());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("gateway" in $$parsedSource) {
            $$parsedSource["gateway"] = $$createField0_0($$parsedSource["gateway"]);
        }
        if ("workspace" in $$parsedSource) {
            $$parsedSource["workspace"] = $$createField1_0($$parsedSource["workspace"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField2_0($$parsedSource["ui"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

export class UISettings {
    /**
     * Creates a new UISettings instance.
     * @param {Partial<UISettings>} [$$source = {}] - The source object to create the UISettings.
     */
    constructor($$source = {}) {
        if (!("showTimestamps" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showTimestamps"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UISettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UISettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UISettings(/** @type {Partial<UISettings>} */($$parsedSource));
    }
}

export class WorkspaceSettings {
    /**
     * Creates a new WorkspaceSettings instance.
     * @param {Partial<WorkspaceSettings>} [$$source = {}] - The source object to create the WorkspaceSettings.
     */
    constructor($$source = {}) {
        if (!("rootDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceSettings(/** @type {Partial<WorkspaceSettings>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = GatewaySettings.createFrom;
const $$createType1 = WorkspaceSettings.createFrom;
const $$createType2 = UISettings.createFrom;
