// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as ConfigService from "./configservice.js";
import * as SystemService from "./systemservice.js";
export {
    ConfigService,
    SystemService
};

export {
    AppInfo,
    ConfigPayload
} from "./models.js";
