// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseDirectory() {
    return $Call.ByID(1479459780);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseGatewayConfig() {
    return $Call.ByID(4196354359);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseGatewayProgram() {
    return $Call.ByID(2281124027);
}

/**
 * @param {string} baseURL
 * @returns {$CancellablePromise<boolean>}
 */
export function EnsureBundledGateway(baseURL) {
    return $Call.ByID(2140587032, baseURL);
}

/**
 * @returns {$CancellablePromise<$models.AppInfo | null>}
 */
export function GetAppInfo() {
    return $Call.ByID(1878648571).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AppInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
